# true for enabling L2Eve geodriver
L2EveGeoDataDriverEnabled = false

# Class driver implementation
L2EveGeoDataDriverClass = ru.mosinnik.l2eve.geodriver.driver.GeoDriver
#L2EveGeoDataDriverClass = ru.mosinnik.l2eve.geodriver.driver.GeoDriverBytes
#L2EveGeoDataDriverClass = ru.mosinnik.l2eve.geodriver.driver.GeoDriverBytesMmap

# Relative path to binary geodata for GeoDriverBytes
GeoDataBinPath = ./geodata_bin

# use .l2j files to load GeoDriverBytes
LoadBytesFromL2J = true
# generate binaries after .l2j loading in GeoDriverBytes
GenerateBinFromL2J = false

# GeoConfig options
REUSE_FLAT_BLOCK_ENABLED = true
ONE_HEIGHT_COMPLEX_BLOCK_ENABLED = true
FEW_HEIGHTS_ONE_NSWE_COMPLEX_BLOCK_ENABLED = false
FEW_HEIGHTS_COMPLEX_BLOCK_ENABLED = false
BASE_HEIGHT_COMPLEX_BLOCK_ENABLED = false
BASE_HEIGHT_ONE_NSWE_COMPLEX_BLOCK_ENABLED = false
NO_HOLES_MULTILAYER_BLOCK_ENABLED = true
INDEXED_MULTILAYER_BLOCK_ENABLED = true
INDEXED_32_MULTILAYER_BLOCK_ENABLED = true
